#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
NERD_FONT="Hack Nerd Font"
PADDINGS=4 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance and default values
bar=(
	height=20
	color="$TRANSPARENT"
	shadow=on
	position=top
	sticky=on
	padding_right=10
	padding_left=10
	corner_radius=9
	y_offset=5
	margin=10
	blur_radius=20
	notch_width=0
)
sketchybar --bar "${bar[@]}"

default_item=(
	updates=when_shown
	icon.font="$FONT":Bold:14.0
	icon.color="$ICON_COLOR"
	icon.padding_left="$PADDINGS"
	icon.padding_right=2
	label.font="$FONT":Semibold:13.0
	label.color="$LABEL_COLOR"
	label.padding_left="$PADDINGS"
	label.padding_right="$PADDINGS"
	padding_right="$PADDINGS"
	padding_left="$PADDINGS"
	background.height=30
	background.corner_radius=9
	popup.background.border_width=2
	popup.background.corner_radius=9
	popup.background.border_color="$POPUP_BORDER_COLOR"
	popup.background.color="$POPUP_BACKGROUND_COLOR"
	popup.background.shadow.drawing=on
)
sketchybar --default "${default_item[@]}"

separator() {
	sketchybar --add item seperator.l"$1" right \
		--set seperator.l"$1" padding_left=10 \
		padding_right=5 \
		background.drawing=off \
		icon.drawing=off \
		label.drawing=off
}

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/weather.sh"
# separator 1
# source "$ITEM_DIR/taskwarrior.sh"
# source "$ITEM_DIR/ical.sh"
separator 2
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

source "$ITEM_DIR/network_stat.sh"
source "$ITEM_DIR/cpu.sh"

# Define brackets
default_bracket=(
	background.padding_left=12
	background.padding_right=12
	background.corner_radius=4
	background.height=21
	background.border_color=$WHITE
	background.border_width=1
	background.color="$DARK_BLUE"
)
sketchybar --add bracket work ical taskwarrior \
	--set work background.color="$DARK_BLUE" \
	"${default_bracket[@]}"

sketchybar --add bracket day calendar weather \
	--set day "${default_bracket[@]}"

sketchybar --add bracket system network battery volume volume_icon --set system "${default_bracket[@]}"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
